[dependencies]
anyhow = "1.0"
futures-util = "0.3"
rdkafka = { version = "0.29", features = ["tokio"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.30", features = ["full"] }
tokio-tungstenite = "0.21"